---
- hosts: hanas

  vars:
    sap_hana_ha_pacemaker_hana_sid: RH1
    sap_hana_ha_pacemaker_hana_instance_number: "01"
    sap_hana_ha_pacemaker_vip: 192.168.47.100
    sap_hana_ha_pacemaker_hacluster_password: "Mysecretpassword"
    sap_hana_ha_pacemaker_node1_fqdn: hana-qb9vf1.example.com
    sap_hana_ha_pacemaker_node2_fqdn: hana-qb9vf2.example.com
    sap_hana_ha_pacemaker_node1_ip: 192.168.47.112
    sap_hana_ha_pacemaker_node2_ip: 192.168.47.55

  roles:
    - redhat_sap.sap_hana_ha_pacemaker
